# Generated by Django 5.1.2 on 2025-02-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food_App', '0005_fooditem_rating_fooditem_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='rating_count',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_App.registration')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food_App.fooditem')),
            ],
            options={
                'unique_together': {('food_item', 'customer')},
            },
        ),
    ]
